#!/usr/sbin/nft -f
flush ruleset

# eth2 = corp
# eth1 = dmz
# eth0 = internet

add table inet router

add chain inet router forward { type filter hook forward priority 0; policy drop; }
add chain inet router nat { type nat hook postrouting priority srcnat; policy accept; }

add rule inet router forward iifname "eth2" oifname "eth1" accept
add rule inet router forward iifname "eth2" oifname "eth0" accept
add rule inet router forward iifname "eth1" oifname "eth2" ct state established,related accept
add rule inet router forward iifname "eth0" oifname "eth1" tcp dport {3000} accept
add rule inet router forward iifname "eth1" oifname "eth0" ct state established,related accept

add rule inet router nat oifname "eth0" masquerade 
